### ISSUE TITLE
Updating local image

### ISSUE THREAD

**Issue by andrewpbray** [stat20/stat20-docker#9]
Hi @ryanlovett ,

I ran into a puzzling thing while trying to render the course in a local stat20 container. I navigated to the stat20 dir on my machine and ran `make up`. The result:

<img width="589" alt="Screen Shot 2023-07-03 at 7 48 13 AM" src="https://github.com/stat20/stat20-docker/assets/1627362/9e568b54-a294-4126-a139-6c0a4c9874e7">

I was able to interact with the container via localhost in the browser, but when I went to render, it errored out with:

```
there is no package called 'kableExtra'
```

Which is puzzling, because it's present in [stat20-r-packages.r](https://github.com/stat20/stat20-docker/blob/main/stat20-r-packages.r). 

Seems like I'm not pulling down an image that corresponds to this repo. Any ideas of what's going on?

**Comment by ryanlovett** [comment]
@andrewpbray You most likely need to run ‘docker pull stat20/stat20-docket: latest’ to fetch the latest ’latest’.  At some point the textbook workflows should transition to specifying the image hash as the tag rather than ‘latest’ for reproducibility, but this would also cause docker to automatically pull the right image. It was initially set to ‘latest’ because the image needed to be frequently updated, but that should diminish over time.

**Comment by andrewpbray** [comment]
Got it - I'll give that a try (I'm on a slow connection so that download will take awhile).

Is this the sort of thing we could put into into the dockerfile? I see this line:

```
services:
  stat20:
    # `latest` tag is sufficient when developing from master.
    # Pin a SHA when developing production materials.
    image: stat20/stat20-docker:latest
```

But is that just looking a the latest image locally instead of checking that the local image is the same as the latest one available on dockerhub?

**Comment by andrewpbray** [comment]
(yup, the pull worked!)

**Comment by ryanlovett** [comment]
Yes, it would go into the [docker-compose.yml](https://github.com/stat20/stat20/blob/main/docker-compose.yml). Early on when the image was changing all of the time I just kept it at `latest`. I was building the image locally so on my machine, latest was latest, and I never had to pull from upstream.

The docker daemon doesn't consult upstream whether the tag has changed in the registry or not, unless you run `docker pull`. That is one downside of using tags that can be associated with different images over time.
